return {
	mod_name =        { en = "Color My Stamina" },
	mod_description = { en = "Changes stamina bar colors based on percentage." },
	-- Thresholds for changing bar colors
	threshold_1 =     { en = "First Threshold (%%)" },
	threshold_2 =     { en = "Second Threshold (%%)" },
	threshold_3 =     { en = "Third Threshold (%%)" },
	threshold_4 =     { en = "Fourth Threshold (%%)" },
	-- Color for each percentage
	color_1 =         { en = "First Color" },
	color_2 =         { en = "Second Color" },
	color_3 =         { en = "Third Color" },
	color_4 =         { en = "Fourth Color" },
	-- Available colors to choose
	color_red =       { en = "Red" },
	color_orange =    { en = "Orange" },
	color_yellow =    { en = "Yellow" },
	color_green =     { en = "Green" },
	color_blue =      { en = "Blue" },
	color_white =     { en = "White" },
	color_cyan =      { en = "Cyan" },
	color_magenta =   { en = "Magenta" },
	color_purple =    { en = "Purple" },
	color_pink =      { en = "Pink" },
	color_lime =      { en = "Lime" },
	color_teal =      { en = "Teal" },
	color_gold =      { en = "Gold" },
	color_silver =    { en = "Silver" },
	color_black =     { en = "Black" },
}