return {
	mod_name =        { en = "Color My Stamina" },
	mod_description = { en = "Changes stamina bar colors based on percentage." },
	threshold_1 =     { en = "First Threshold (%%)" },
	color_1 =         { en = "First Color" },
	threshold_2 =     { en = "Second Threshold (%%)" },
	color_2 =         { en = "Second Color" },
	threshold_3 =     { en = "Third Threshold (%%)" },
	color_3 =         { en = "Third Color" },
	threshold_4 =     { en = "Fourth Threshold (%%)" },
	color_4 =         { en = "Fourth Color" },
	color_1_red =     { en = "Red" },
	color_1_orange =  { en = "Orange" },
	color_1_yellow =  { en = "Yellow" },
	color_1_green =   { en = "Green" },
	color_1_blue =    { en = "Blue" },
	color_1_white =   { en = "White" },
	color_1_cyan =    { en = "Cyan" },
	color_1_magenta = { en = "Magenta" },
	color_1_purple =  { en = "Purple" },
	color_1_pink =    { en = "Pink" },
	color_1_lime =    { en = "Lime" },
	color_1_teal =    { en = "Teal" },
	color_1_gold =    { en = "Gold" },
	color_1_silver =  { en = "Silver" },
	color_1_black =   { en = "Black" },
	color_2_red =     { en = "Red" },
	color_2_orange =  { en = "Orange" },
	color_2_yellow =  { en = "Yellow" },
	color_2_green =   { en = "Green" },
	color_2_blue =    { en = "Blue" },
	color_2_white =   { en = "White" },
	color_2_cyan =    { en = "Cyan" },
	color_2_magenta = { en = "Magenta" },
	color_2_purple =  { en = "Purple" },
	color_2_pink =    { en = "Pink" },
	color_2_lime =    { en = "Lime" },
	color_2_teal =    { en = "Teal" },
	color_2_gold =    { en = "Gold" },
	color_2_silver =  { en = "Silver" },
	color_2_black =   { en = "Black" },
	color_3_red =     { en = "Red" },
	color_3_orange =  { en = "Orange" },
	color_3_yellow =  { en = "Yellow" },
	color_3_green =   { en = "Green" },
	color_3_blue =    { en = "Blue" },
	color_3_white =   { en = "White" },
	color_3_cyan =    { en = "Cyan" },
	color_3_magenta = { en = "Magenta" },
	color_3_purple =  { en = "Purple" },
	color_3_pink =    { en = "Pink" },
	color_3_lime =    { en = "Lime" },
	color_3_teal =    { en = "Teal" },
	color_3_gold =    { en = "Gold" },
	color_3_silver =  { en = "Silver" },
	color_3_black =   { en = "Black" },
	color_4_red =     { en = "Red" },
	color_4_orange =  { en = "Orange" },
	color_4_yellow =  { en = "Yellow" },
	color_4_green =   { en = "Green" },
	color_4_blue =    { en = "Blue" },
	color_4_white =   { en = "White" },
	color_4_cyan =    { en = "Cyan" },
	color_4_magenta = { en = "Magenta" },
	color_4_purple =  { en = "Purple" },
	color_4_pink =    { en = "Pink" },
	color_4_lime =    { en = "Lime" },
	color_4_teal =    { en = "Teal" },
	color_4_gold =    { en = "Gold" },
	color_4_silver =  { en = "Silver" },
	color_4_black =   { en = "Black" },
}


